# Generated by Django 2.2.7 on 2019-11-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('abuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tios', to='comercio.Abuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Primo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primos', to='comercio.Tio')),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('abuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres', to='comercio.Abuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='comercio.Padre')),
            ],
        ),
    ]
