# Generated by Django 2.2.7 on 2019-11-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0002_abuelo_hijo_padre_primo_tio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hijo',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='abuelo',
        ),
        migrations.RemoveField(
            model_name='primo',
            name='tio',
        ),
        migrations.RemoveField(
            model_name='tio',
            name='abuelo',
        ),
        migrations.DeleteModel(
            name='Abuelo',
        ),
        migrations.DeleteModel(
            name='Hijo',
        ),
        migrations.DeleteModel(
            name='Padre',
        ),
        migrations.DeleteModel(
            name='Primo',
        ),
        migrations.DeleteModel(
            name='Tio',
        ),
    ]
